### PR TITLE
sync-diff-inspector: only enable new collation for data comparison

### LINKED ISSUE #861: sync-diff-inspector: should support tidb clusters with new_collations_enabled_on_first_bootstrap=false
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
a. deploy tidb cluster with config `new_collations_enabled_on_first_bootstrap=false`
b. create table
c. run sync-diff-inspector
  ```sql
  create table t1 (
      id int PRIMARY KEY,
      name varchar(20) COLLATE utf8mb4_0900_as_cs
  );
  ```
 

2. What did you expect to see?
compare success

3. What did you see instead?
```log
[2025/07/03 11:22:51.857 -04:00] [INFO] [printer.go:46] ["Welcome to sync_diff_inspector"] ["Release Version"=v7.5.6-2-ga611536] ["Git Commit Hash"=a611536696221844eeb8ec5a9a2e90ca87223a54] ["Git Branch"=master] ["UTC Build Time"="2025-06-03 06:19:35"] ["Go Version"=go1.23.3]
[2025/07/03 11:22:51.858 -04:00] [INFO] [main.go:101] [config="{\"check-thread-count\":4,\"split-thread-count\":5,\"export-fix-sql\":true,\"check-struct-only\":false,\"dm-addr\":\"\",\"dm-task\":\"\",\"data-sources\":{\"eks\":{\"host\":\"127.0.0.1\",\"port\":4000,\"user\":\"root\",\"password\":\"******\",\"sql-mode\":\"\",\"snapshot\":\"\",\"sql-hint-use-index\":\"\",\"security\":null,\"route-rules\":null,\"Router\":{\"Selector\":{}},\"Conn\":null,\"session\":null},\"teletraan\":{\"host\":\"127.0.0.1\",\"port\":3306,\"user\":\"root\",\"password\":\"******\",\"sql-mode\":\"\",\"snapshot\":\"\",\"sql-hint-use-index\":\"\",\"security\":null,\"route-rules\":null,\"Router\":{\"Selector\":{}},\"Conn\":null,\"session\":null}},\"routes\":null,\"table-configs\":{\"config1\":{\"target-tables\":[\"featured_boards.boards\"],\"Schema\":\"\",\"Table\":\"\",\"ConfigIndex\":0,\"HasMatched\":false,\"IgnoreColumns\":[\"countries\",\"languages\",\"genders\",\"ages\",\"board_tag_ids\",\"search_terms\",\"metadata\"],\"Fields\":null,\"Range\":\"\",\"TargetTableInfo\":null,\"Collation\":\"\",\"chunk-size\":1000}},\"task\":{\"source-instances\":[\"teletraan\"],\"source-routes\":null,\"target-instance\":\"eks\",\"target-check-tables\":[\"featured_boards.boards\"],\"target-configs\":[\"config1\"],\"output-dir\":\"./output\",\"SourceInstances\":[{\"host\":\"127.0.0.1\",\"port\":3306,\"user\":\"root\",\"password\":\"******\",\"sql-mode\":\"\",\"snapshot\":\"\",\"sql-hint-use-index\":\"\",\"security\":null,\"route-rules\":null,\"Router\":{\"Selector\":{}},\"Conn\":null,\"session\":null}],\"TargetInstance\":{\"host\":\"127.0.0.1\",\"port\":4000,\"user\":\"root\",\"password\":\"******\",\"sql-mode\":\"\",\"snapshot\":\"\",\"sql-hint-use-index\":\"\",\"security\":null,\"route-rules\":null,\"Router\":{\"Selector\":{}},\"Conn\":null,\"session\":null},\"TargetTableConfigs\":[{\"target-tables\":[\"featured_boards.boards\"],\"Schema\":\"\",\"Table\":\"\",\"ConfigIndex\":0,\"HasMatched\":false,\"IgnoreColumns\":[\"countries\",\"languages\",\"genders\",\"ages\",\"board_tag_ids\",\"search_terms\",\"metadata\"],\"Fields\":null,\"Range\":\"\",\"TargetTableInfo\":null,\"Collation\":\"\",\"chunk-size\":1000}],\"TargetCheckTables\":[{}],\"FixDir\":\"output/fix-on-eks\",\"CheckpointDir\":\"output/checkpoint\",\"HashFile\":\"\"},\"ConfigFile\":\"../config.toml\",\"PrintVersion\":false}"]
[2025/07/03 11:22:51.869 -04:00] [FATAL] [main.go:121] ["failed to initialize diff process"] [error="get table featured_boards.boards's information error [ddl:1273]Unsupported collation when new collation is enabled: 'utf8mb4_0900_as_cs'
github.com/pingcap/errors.AddStack
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/errors.go:178
github.com/pingcap/errors.(*Error).GenWithStackByArgs
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/normalize.go:175
github.com/pingcap/tidb/pkg/util/collate.GetCollationByName
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20241119124618-50b5cd27d413/pkg/util/collate/collate.go:238
github.com/pingcap/tidb/pkg/ddl.getCharsetAndCollateInColumnDef
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20241119124618-50b5cd27d413/pkg/ddl/add_column.go:332
github.com/pingcap/tidb/pkg/ddl.buildColumnAndConstraint
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20241119124618-50b5cd27d413/pkg/ddl/add_column.go:296
github.com/pingcap/tidb/pkg/ddl.buildColumnsAndConstraints
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20241119124618-50b5cd27d413/pkg/ddl/create_table.go:972
github.com/pingcap/tidb/pkg/ddl.BuildTableInfoWithStmt
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20241119124618-50b5cd27d413/pkg/ddl/create_table.go:722
github.com/pingcap/tidb-tools/pkg/dbutil.getTableInfoBySQL
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/pkg/dbutil/table.go:154
github.com/pingcap/tidb-tools/pkg/dbutil.GetTableInfoBySQLWithSessionContext
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/pkg/dbutil/table.go:137
github.com/pingcap/tidb-tools/pkg/dbutil.GetTableInfoWithVersion
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/pkg/dbutil/table.go:118
github.com/pingcap/tidb-tools/sync_diff_inspector/source.initTables
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/source/source.go:338
github.com/pingcap/tidb-tools/sync_diff_inspector/source.NewSources
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/source/source.go:121
main.(*Diff).init
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/diff.go:137
main.NewDiff
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/diff.go:95
main.checkSyncState
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/main.go:117
main.main
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/main.go:104
runtime.main
  /usr/local/go/src/runtime/proc.go:272
runtime.goexit
  /usr/local/go/src/runtime/asm_amd64.s:1700"] [errorVerbose="get table featured_boards.boards's information error [ddl:1273]Unsupported collation when new collation is enabled: 'utf8mb4_0900_as_cs'
github.com/pingcap/errors.AddStack
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/errors.go:178
github.com/pingcap/errors.(*Error).GenWithStackByArgs
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/normalize.go:175
github.com/pingcap/tidb/pkg/util/collate.GetCollationByName
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20241119124618-50b5cd27d413/pkg/util/collate/collate.go:238
github.com/pingcap/tidb/pkg/ddl.getCharsetAndCollateInColumnDef
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20241119124618-50b5cd27d413/pkg/ddl/add_column.go:332
github.com/pingcap/tidb/pkg/ddl.buildColumnAndConstraint
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20241119124618-50b5cd27d413/pkg/ddl/add_column.go:296
github.com/pingcap/tidb/pkg/ddl.buildColumnsAndConstraints
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20241119124618-50b5cd27d413/pkg/ddl/create_table.go:972
github.com/pingcap/tidb/pkg/ddl.BuildTableInfoWithStmt
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20241119124618-50b5cd27d413/pkg/ddl/create_table.go:722
github.com/pingcap/tidb-tools/pkg/dbutil.getTableInfoBySQL
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/pkg/dbutil/table.go:154
github.com/pingcap/tidb-tools/pkg/dbutil.GetTableInfoBySQLWithSessionContext
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/pkg/dbutil/table.go:137
github.com/pingcap/tidb-tools/pkg/dbutil.GetTableInfoWithVersion
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/pkg/dbutil/table.go:118
github.com/pingcap/tidb-tools/sync_diff_inspector/source.initTables
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/source/source.go:338
github.com/pingcap/tidb-tools/sync_diff_inspector/source.NewSources
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/source/source.go:121
main.(*Diff).init
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/diff.go:137
main.NewDiff
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/diff.go:95
main.checkSyncState
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/main.go:117
main.main
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/main.go:104
runtime.main
  /usr/local/go/src/runtime/proc.go:272
runtime.goexit
  /usr/local/go/src/runtime/asm_amd64.s:1700
github.com/pingcap/tidb-tools/sync_diff_inspector/source.initTables
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/source/source.go:340
github.com/pingcap/tidb-tools/sync_diff_inspector/source.NewSources
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/source/source.go:121
main.(*Diff).init
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/diff.go:137
main.NewDiff
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/diff.go:95
main.checkSyncState
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/main.go:117
main.main
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/main.go:104
runtime.main
  /usr/local/go/src/runtime/proc.go:272
runtime.goexit
  /usr/local/go/src/runtime/asm_amd64.s:1700"] [stack="main.checkSyncState
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/main.go:121
main.main
  /home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/main.go:104
runtime.main
  /usr/local/go/src/runtime/proc.go:272"]
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

5. which tool are you using?
sync-diff-inspector
6. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: close #861

### What is changed and how it works?

Previously, we disable new collation in sync-diff-inspector by default, and add necessary collation in `main.go`

After #853, we enable new collation by default to support data comparison using certain collation. But here we miss the fact that TiDB server can disable new collation through `new_collations_enabled_on_first_bootstrap`. So we should check this value of TiDB to decide whether apply collation in data comparison.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code
 
 Manually test the given case in #861, and should succeed.

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

File: pkg/dbutil/common.go [hunk 1]
```diff
@@ -32,13 +32,19 @@ import (
...
 	"github.com/pingcap/tidb/pkg/util/dbterror"
 	"go.uber.org/zap"
 
 	"github.com/pingcap/tidb-tools/pkg/utils"
 )
 
+func init() {
+	// disable new collation by default to pass table struct parsing
+	collate.SetNewCollationEnabledForTest(false)
+}
```
Comment (kennytm) [inline pkg/dbutil/common.go]: 👀 looks dangerous, is the `dbutil` package used by any other tools?

Comment (joechenrh) [reply pkg/dbutil/common.go]: Just revert the code change (https://github.com/pingcap/tidb-tools/pull/853/files#diff-a33cfec0ca3f5df3fe2e367eb7cad3d25edbd04fa028bf4af55d6be5ea332c46L44-L47).
 
 Moved to `main.go` to avoid potential issues https://github.com/pingcap/tidb-tools/pull/862/commits/a1cdbd34a9780712d9f909221d7f82ab0d2292c0

**Review by JQWong7 — APPROVED** [review]
test case part LGTM

**Review by kennytm — APPROVED** [review]
