### PR TITLE
sync_diff_inspector: process special character in generated fix SQL

### LINKED ISSUE #833: some line breaks and backslashes are missing in fix.sql generated by sync-diff-inspector
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
1、upstream database :  varchar field contains some newlines and backslashes (\\\)
2、downstream database : varchar field contains some newlines and backslashes (\)
3、then use sync-diff-inspector compare data,
4、Some line breaks and backslashes are missing in the _**fix.sql**_ 

2. What did you expect to see?
fix.sql have all line breaks and backslashes , just like upsteams data row.

3. What did you see instead?
Some line breaks and backslashes are missing in the _**fix.sql**_ 

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
upstream : v3.0.8
downstream: v6.5.7
sync-diff-inspector : v6.5.3

5. which tool are you using?
sync-diff-inspector : v6.5.3

6. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: close #833

### What is changed and how it works?

Add missing process for characters like backslashes (\\) in fix SQL.

### Check List 

Tests 

 - Unit test
 - Integration test

Related changes

 - Need to be included in the release note

```
process special characters like backslashes in generated fix SQL.
```

### CODE REVIEW

**Review by kennytm — APPROVED** [review]

File: sync_diff_inspector/utils/utils.go [hunk 1]
```diff
@@ -172,6 +172,14 @@ func GetTableRowsQueryFormat(schema, table string, tableInfo *model.TableInfo, c
 	return query, orderKeyCols
 }
 
+// escapeString escapes special characters in the given string
+func escapeString(bs []byte) string {
+	s := string(bs)
+	s = strings.Replace(s, "\\", "\\\\", -1)
+	s = strings.Replace(s, "'", "\\'", -1)
+	return s
```
Comment (D3Hunter) [inline sync_diff_inspector/utils/utils.go:180]: any reference for the escape rule? do we need to handle new line? I see the issue mention it `Some line breaks and backslashes are missing in the fix.sql`

Comment (joechenrh) [reply sync_diff_inspector/utils/utils.go:180]: I've added linebreaks and backslashes in the UT:
https://github.com/pingcap/tidb-tools/pull/846/files#diff-27471957ca7f3cc0b159ef57928a0bcbb7de33a4cbe224bb48d3f81c6085da91R350-R351
And I also did some tests locally. Let me add an integration test.

Comment (kennytm) [reply sync_diff_inspector/utils/utils.go:180]: if you also need to escape `\n` and `\r` etc perhaps just `import "github.com/pingcap/tidb/util/format"` and use its `OutputFormat` function

Comment (joechenrh) [reply sync_diff_inspector/utils/utils.go:180]: > if you also need to escape \n and \r

Since the input is a byte slice, I think we don't need additional process for `\n` and `\r`?

Comment (D3Hunter) [reply sync_diff_inspector/utils/utils.go:180]: > Since the input is a byte slice

so this slice cannot contain newline in binary?

Comment (D3Hunter) [reply sync_diff_inspector/utils/utils.go:180]: seems ok to have raw newline in sql, like 
```sql
insert into t values('a
a');
```

**Review by D3Hunter — APPROVED** [review]

File: sync_diff_inspector/utils/utils.go (hunk 1 above)
Comment (kennytm) [reply sync_diff_inspector/utils/utils.go:180]: @joechenrh I don't see why a `[]byte` cannot contain \x0D (\r) or \x0A (\n).

Comment (joechenrh) [reply sync_diff_inspector/utils/utils.go:180]: @kennytm  Sorry for the late reply, I missed the message.

I mean, we don't need to escape `\n`. Just like the example in the comment above, we can directly add raw newline in SQL:

```sql
mysql> insert into test.t1 values(1, "a\"
    "> \\1'`_%!");
Query OK, 1 row affected (0.01 sec)

mysql> select * from test.t1;
+------+------------+
| id   | col1       |
+------+------------+
|    1 | a"
\1'`_%! |
+------+------------+
1 row in set (0.00 sec)
```
