### PR TITLE
sync-diff-inspector: apply collation to columns with non-binary charset

### LINKED ISSUE #759: diff: collation is applied incorrectly in ORDER BY when the primary key is composite
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
-- mysql @ 172.17.0.2:3306
create table t (a varchar(200) collate utf8mb4_general_ci not null, b varchar(200) collate utf8mb4_bin not null, primary key(a, b));
insert into t values ('a', 'aa'), ('B', 'bb'), ('c', 'cc'), ('D', 'dd'), ('e', 'ee'), ('F', 'ff'), ('g', 'gg'), ('H', 'hh'), ('*', 'mysql');

-- tidb @ 127.0.0.1:4000
create table t (a varchar(200) collate utf8mb4_bin not null, b varchar(200) collate utf8mb4_bin not null, primary key(a, b));
insert into t values ('a', 'aa'), ('B', 'bb'), ('c', 'cc'), ('D', 'dd'), ('e', 'ee'), ('F', 'ff'), ('g', 'gg'), ('H', 'hh'), ('*', 'tidb');
```

```toml
[data-sources.src1]
host = '172.17.0.2'
port = 3306
user = 'root'
password = '111'

[data-sources.src2]
host = '127.0.0.1'
port = 4000
user = 'root'
password = ''

[task]
output-dir = './output'
source-instances = ['src1']
target-instance = 'src2'
target-check-tables = ['test.t']
target-configs = ['cfg1']

[table-configs.cfg1]
target-tables = ['test.t']
collation = 'utf8mb4_general_ci'
```

```sh
bin/sync_diff_inspector -C cfg.toml
```

2. What did you expect to see?

Only 1 row differs

```
+------------+---------+--------------------+----------------+---------+-----------+
|   TABLE    | RESULT  | STRUCTURE EQUALITY | DATA DIFF ROWS | UPCOUNT | DOWNCOUNT |
+------------+---------+--------------------+----------------+---------+-----------+
| `test`.`t` | succeed | true               | +1/-1          |       9 |         9 |
+------------+---------+--------------------+----------------+---------+-----------+
```

4. What did you see instead?

5 row differs.

```
+------------+---------+--------------------+----------------+---------+-----------+
|   TABLE    | RESULT  | STRUCTURE EQUALITY | DATA DIFF ROWS | UPCOUNT | DOWNCOUNT |
+------------+---------+--------------------+----------------+---------+-----------+
| `test`.`t` | succeed | true               | +5/-5          |       9 |         9 |
+------------+---------+--------------------+----------------+---------+-----------+
```

5. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

7.3.0

6. which tool are you using?

sync-diff-inspector 7.1.3 (master version 8811722d71222462578c24da878a59ca46c8baaf)

7. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

### LINKED ISSUE #760: diff: collation should not be applied on non-string columns
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
-- mysql @ 172.17.0.2:3306
create table u (a int primary key);
insert into u values (1), (2);

-- tidb @ 127.0.0.1:4000
create table u (a int primary key);
insert into u values (1), (2);
```

```toml
[data-sources.src1]
host = '172.17.0.2'
port = 3306
user = 'root'
password = '111'

[data-sources.src2]
host = '127.0.0.1'
port = 4000
user = 'root'
password = ''

[task]
output-dir = './output'
source-instances = ['src1']
target-instance = 'src2'
target-check-tables = ['test.u']
target-configs = ['cfg1']

[table-configs.cfg1]
target-tables = ['*.*']
collation = 'utf8mb4_general_ci'
chunk-size = 1
```

```sh
bin/sync_diff_inspector -C cfg.toml
```

2. What did you expect to see?

The two `test.u` tables are equivalent

4. What did you see instead?

Fatal error.

```
[2023/12/28 01:37:05.737 +08:00] [FATAL] [main.go:139] ["failed to check data difference"] [error="Error 1253 (42000): COLLATION 'utf8mb4_general_ci' is not valid for CHARACTER SET 'binary'"] 

```

5. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

7.3.0

6. which tool are you using?

sync-diff-inspector 7.1.3 (master version 8811722d71222462578c24da878a59ca46c8baaf)

7. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: close #759, close #760

### What is changed and how it works?

This PR fix two problems:

- When generating SQL, we should check the charset of columns. Collation can only applied to non-binary columns.
- In order by clause, collation should be applied to all available columns.

Also, when comparing rows, if case-insensitive collation is applied to row iterator, we should also take collation into consideration in `CompareData`. If not, the following test case will return 3 rows rather than 2 rows:

```SQL
+---+---+   +---+----+
| a | b |   | a | b  |
+---+---+   +---+----+
| a | 2 |   | a |  1 |
| B | 2 |   | B |  2 |
| c | 4 |   | c |  4 |
| D | 3 |   | D | 33 |
+---+---+   +---+----+
```

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

File: sync_diff_inspector/diff.go [hunk 1]
```diff
@@ -626,6 +626,12 @@ func (df *Diff) compareChecksumAndGetCount(ctx context.Context, tableRange *spli
 }
 
 func (df *Diff) compareRows(ctx context.Context, rangeInfo *splitter.RangeInfo, dml *ChunkDML) (bool, error) {
+	collation := df.upstream.GetTables()[rangeInfo.GetTableIndex()].Collation
+	ci := false
+	if collation != "" && strings.Contains(strings.ToLower(collation), "ci") {
+		ci = true
+	}
```
Comment (kennytm) [inline sync_diff_inspector/diff.go]: Knowing whether a collation is case-insensitive is insufficient to deduce the `CompareData()` order. For instance:

```sql
mysql> select 'æ' collate utf8mb4_unicode_ci < 'b', 'æ' collate utf8mb4_general_ci < 'b' \G
*************************** 1. row ***************************
'æ' collate utf8mb4_unicode_ci < 'b': 1
'æ' collate utf8mb4_general_ci < 'b': 0
1 row in set (0.00 sec)
```

you *need* to pass the entire collation into `CompareData`.

Comment (joechenrh) [reply sync_diff_inspector/diff.go]: Yeah, so we should convert it to `types.Datum` for comparison.

Comment (joechenrh) [reply sync_diff_inspector/diff.go]: Fixed, PTAL

**Review by kennytm — APPROVED** [review]
