### PR TITLE
diff: increase connection limit according to number of shard tables

### LINKED ISSUE #411: sync-diff stuck
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8185/pipeline/90

2. What did you expect to see?

finish in time

3. What did you see instead?

stuck

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

5. which tool are you using?

sync-diff

6. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

nightly

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
close #411

### What is changed and how it works?
one chunk need accessing every shard tables in one upstream,  and there are `CheckThreadCount` simultaneously processing chunks. Adjust connection limit to fix the worst case which needs `CheckThreadCount` * number of shard tables connections.

### Check List 

Tests 

 - Integration test
 - Manual test (an integration test of DM could pass)

Code changes

Side effects

Related changes

 - Need to be included in the release note

### CODE REVIEW

File: pkg/diff/diff.go [hunk 1]
```diff
@@ -621,6 +621,9 @@ func (t *TableDiff) compareRows(ctx context.Context, chunk *ChunkRange) (bool, e
 
 				}
 				// still don't have data, means the rows is read to the end, so delete the source
+				if err := sourceRows[i].Close(); err != nil {
+					return nil, err
+				}
```
Comment (kennytm) [inline pkg/diff/diff.go]: 🤔 what to do with the `defer rows.Close()` in line 574 then

**Comment by lance6716** [comment]
changed the behaviour and PR description. Happy Chinese New Year

**Review by lichunzhu — COMMENTED** [review]
/lgtm

**Review by 3pointer — COMMENTED** [review]
LGTM

**Review by 3pointer — APPROVED** [review]
